#!/bin/sh
#
# Copyright (c) 2014, 2021, The Linux Foundation. All rights reserved.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC
#

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq96xx_setup_interfaces()
{
	local board="$1"

	case "$board" in
	 qcom,ipq9650-rdp488 |\
	 qcom,ipq9650-rdp489 |\
	 qcom,ipq9650-rdp490 |\
	 qcom,ipq9650-rdp491 |\
	 qcom,ipq9650-rdp506 |\
	 qcom,ipq9650-db-ju01|\
	 qcom,ipq9650-db-ju01-c1|\
	 qcom,ipq9650-db-ju02)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
	 	;;
	 *)
	 	echo "Unsupported hardware. Network interfaces not intialized"
	 	;;
	 esac
}

board_config_update
board=$(board_name)
ipq96xx_setup_interfaces $board
board_config_flush

exit 0
