#!/bin/sh
#
# Copyright (c) 2014, 2021, The Linux Foundation. All rights reserved.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC
#

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq96xx_setup_interfaces()
{
	local board="$1"
	local has_qce2204=0
	local port_count=0
	local lan_ifaces=""

	# Check if qce2204 is present
	if grep -q "qce2204" /proc/device-tree/soc@0/*/switch0@*/compatible 2>/dev/null; then
		has_qce2204=1
		# Count the number of ports
		port_count=$(ls /proc/device-tree/soc@0/*/switch0@*/ports/port@*/name 2>/dev/null | wc -l)

		# Build lan interface list based on port count without port@0
		local i=1
		while [ $i -lt $port_count ]; do
			if [ -n "$lan_ifaces" ]; then
				lan_ifaces="$lan_ifaces lan$i"
			else
				lan_ifaces="lan$i"
			fi
			i=$((i + 1))
		done
	fi

	case "$board" in
	 qcom,ipq9650-rdp488 |\
	 qcom,ipq9650-rdp488-c2 |\
	 qcom,ipq9650-rdp489 |\
	 qcom,ipq9650-rdp490 |\
	 qcom,ipq9650-rdp491 |\
	 qcom,ipq9650-rdp506 |\
	 qcom,ipq9650-rdp507 |\
	 qcom,ipq9650-rdp529 |\
	 qcom,ipq9650-rdp530 |\
	 qcom,ipq9650-rdp532 |\
	 qcom,ipq9650-db-ju01|\
	 qcom,ipq9650-db-ju01-c1|\
	 qcom,ipq9650-tb-ju01.1|\
	 qcom,ipq9650-db-ju02)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
	 	;;
	 qcom,ipq9650-db-ju01-c2)
		if [ "$has_qce2204" = "1" ]; then
			ucidef_set_interfaces_lan_wan "eth1 $lan_ifaces" "eth2"
		else
			ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
		fi
		;;
	 *)
	 	echo "Unsupported hardware. Network interfaces not intialized"
	 	;;
	 esac
}

board_config_update
board=$(board_name)
ipq96xx_setup_interfaces $board
board_config_flush

exit 0
