#!/bin/sh
#
# Copyright (c) 2014, 2021, The Linux Foundation. All rights reserved.
# Copyright (c) 2023-2024, Qualcomm Innovation Center, Inc. All rights reserved.
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#


[ -e /etc/config/network ] && exit 0

touch /etc/config/network

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq54xx_setup_interfaces()
{
	local num_iface="$(ls /proc/device-tree/soc*/dp*/name |wc -l)"
	local has_qce2204=0
	local port_count=0
	local lan_ifaces=""

	# Check if qce2204 is present
	if grep -q "qce2204" /proc/device-tree/soc@0/*/switch0@*/compatible 2>/dev/null; then
		has_qce2204=1
		# Count the number of ports
		port_count=$(ls /proc/device-tree/soc@0/*/switch0@*/ports/port@*/name 2>/dev/null | wc -l)

		# Build lan interface list based on port count without port@0
		local i=1
		while [ $i -lt $port_count ]; do
			if [ -n "$lan_ifaces" ]; then
				lan_ifaces="$lan_ifaces lan$i"
			else
				lan_ifaces="lan$i"
			fi
			i=$((i + 1))
		done
	fi

	case "$num_iface" in
	6)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
		;;
	5)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4" "eth0"
		;;
	3)
		if [ "$has_qce2204" = "1" ]; then
			ucidef_set_interfaces_lan_wan "eth1 $lan_ifaces" "eth0"
		else
			ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
			ucidef_add_switch "switch1"
			ucidef_add_switch_attr "switch1" "enable" false
		fi
		;;
	2)
		if [ "$has_qce2204" = "1" ]; then
			ucidef_set_interfaces_lan_wan "$lan_ifaces" "eth0"
		else
			ucidef_set_interfaces_lan_wan "eth1" "eth0"
			ucidef_add_switch "switch1"
			ucidef_add_switch_attr "switch1" "enable" false
		fi
		;;
	*)
		echo "Unsupported hardware. Network interfaces not intialized"
		;;
	esac
}

board_config_update
ipq54xx_setup_interfaces
board_config_flush

exit 0
