#!/bin/sh
#
# Copyright (c) 2014, 2021, The Linux Foundation. All rights reserved.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC
#

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq52xx_setup_interfaces()
{
	local board="$1"
	local has_qce2204=0
	local port_count=0
	local lan_ifaces=""

	# Check if qce2204 is present
	if grep -q "qce2204" /proc/device-tree/soc@0/*/switch0@*/compatible 2>/dev/null; then
		has_qce2204=1
		# Count the number of ports
		port_count=$(ls /proc/device-tree/soc@0/*/switch0@*/ports/port@*/name 2>/dev/null | wc -l)

		# Build lan interface list based on port count without port@0
		local i=1
		while [ $i -lt $port_count ]; do
			if [ -n "$lan_ifaces" ]; then
				lan_ifaces="$lan_ifaces lan$i"
			else
				lan_ifaces="lan$i"
			fi
			i=$((i + 1))
		done
	fi

	case "$board" in
	qcom,ipq5210-rdp512 |\
	qcom,ipq5210-rdp497)
		if [ "$has_qce2204" = "1" ]; then
			ucidef_set_interfaces_lan_wan "eth1 $lan_ifaces" "eth2"
		else
			ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
		fi
		;;
	qcom,ipq5210-rdp501)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3" "eth0"
	 	;;
	qcom,ipq5210-rdp498 |\
	qcom,ipq5210-rdp500 |\
	qcom,ipq5210-rdp502 |\
	qcom,ipq5210-rdp504 |\
	qcom,ipq5210-rdp511)
	 	ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4" "eth0"
		;;
	qcom,ipq5210-db-hm01.1 |\
	qcom,ipq5210-db-hm02.1 |\
	qcom,ipq5210-rdp499 |\
	qcom,ipq5210-rdp503)
		ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
                ;;
	qcom,ipq5210-rdp505)
		ucidef_set_interfaces_lan_wan "eth1" "eth0"
		ucidef_add_switch "switch1"
		ucidef_add_switch_attr "switch1" "enable" false
	 	;;
	 *)
	 	echo "Unsupported hardware. Network interfaces not intialized"
	 	;;
	 esac
}

board_config_update
board=$(board_name)
ipq52xx_setup_interfaces $board
board_config_flush

exit 0
