#!/bin/sh
#
# Copyright (c) 2014, 2021, The Linux Foundation. All rights reserved.
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: ISC
#

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

CFG=/etc/board.json

. /lib/functions/uci-defaults.sh

ipq52xx_setup_interfaces()
{
	local board="$1"
 
	case "$board" in
	qcom,ipq5210-db-hm01-c1 |\
	qcom,ipq5210-db-hm01-c2 |\
	qcom,ipq5210-ap-hm01-c1)
	 	ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4 eth5" "eth0"
	 	;;
	qcom,ipq5210-ap-hm02-c1 |\
	qcom,ipq5210-ap-hm02-c2 |\
	qcom,ipq5210-ap-hm02-c3 |\
	qcom,ipq5210-ap-hm03-c1 |\
	qcom,ipq5210-ap-hm03-c2 |\
	qcom,ipq5210-ap-hm03-c3 |\
	qcom,ipq5210-ap-hm03-c4 |\
	qcom,ipq5210-ap-hm04-c1)
	 	ucidef_set_interfaces_lan_wan "eth1 eth2 eth3 eth4" "eth0"
	 	;;
	qcom,ipq5210-ap-hm05-c1) |\
	qcom,ipq5210-ap-hm05-c2)
	 	ucidef_set_interfaces_lan_wan "eth1 eth2" "eth0"
	 	ucidef_add_switch "switch1"
	 	ucidef_add_switch_attr "switch1" "enable" false
	 	;;
	 *)
	 	echo "Unsupported hardware. Network interfaces not intialized"
	 	;;
	 esac
}
 
board_config_update
board=$(board_name)
ipq52xx_setup_interfaces $board
board_config_flush
 
exit 0